[features]
seeds = false
skip-lint = false
[programs.localnet]
deal_contract = "9kpWdyR2qtNT21MhLRTBbT21v5thz9hhB3zaPUhr6tbE"
[programs.devnet]
deal_contract = "9kpWdyR2qtNT21MhLRTBbT21v5thz9hhB3zaPUhr6tbE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/solana/key-pair-devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
