[features]
seeds = false
skip-lint = false
[programs.devnet]
deal_contract = "9kpWdyR2qtNT21MhLRTBbT21v5thz9hhB3zaPUhr6tbE"
[programs.localnet]
deal_contract = "GKNkN4uDJWmidEC9h5Q9GQXNg48Go6q5bdnkDj6bSopz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/solana/upgrade_authority.json"

[test]
startup_wait = 10000

[[test.genesis]]
address = "GKNkN4uDJWmidEC9h5Q9GQXNg48Go6q5bdnkDj6bSopz"
program = "target/deploy/deal_contract.so"

[test.validator]
url = "https://api.mainnet-beta.solana.com"     # This is the url of the cluster that accounts are cloned from (See `test.validator.clone`).

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" 
[[test.validator.account]]
address = "9479m8V6EuvFKPC812s8BZ3g3hD5Ru63hkR23Y7DLvEs"
filename = "tests/keys/alt.json"
[[test.validator.mint]]
address = "2w1cBfq2PNPCk8KjK2j9oaMJjZUa4pkSNTCrfeB7cYRt" 

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
