[features]
seeds = false
skip-lint = false
[programs.localnet]
deal_contract = "4Ptc1sVSJHSwv6L2RmefRjezVw6LELuKEvJYdZyyRJN1"
[programs.devnet]
deal_contract = "4Ptc1sVSJHSwv6L2RmefRjezVw6LELuKEvJYdZyyRJN1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/solana/key-pair-devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
